/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ImageToStl.com_T_shirt_gltf.glb --transform --types 
Files: public/models/ImageToStl.com_T_shirt_gltf.glb [8.22MB] > C:\Users\Joseph Segoviano\3D Objects\Caminsas-Web\mi-tienda-camisas\ImageToStl.com_T_shirt_gltf-transformed.glb [1.55MB] (81%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Ribbing_Node: THREE.Mesh
  }
  materials: {
    Body_FRONT_26640: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ImageToStl.com_T_shirt_gltf-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ribbing_Node.geometry} material={materials.Body_FRONT_26640} />
    </group>
  )
}

useGLTF.preload('/ImageToStl.com_T_shirt_gltf-transformed.glb')
