/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ImageToStl.com_T_shirt_gltf.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ImageToStl.com_T_shirt_gltf.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ribbing_Node.geometry} material={materials.Body_FRONT_26640}>
        <mesh geometry={nodes.Ribbing_Node_2.geometry} material={materials.Body_FRONT_26640} />
        <mesh geometry={nodes.Ribbing_Node_3.geometry} material={materials.Body_FRONT_26640} />
      </mesh>
      <mesh geometry={nodes.Ribbing_Node_1.geometry} material={materials.Body_FRONT_26640}>
        <mesh geometry={nodes.Ribbing_Node_4.geometry} material={materials.Body_FRONT_26640} />
        <mesh geometry={nodes.Ribbing_Node_5.geometry} material={materials.Body_FRONT_26640} />
      </mesh>
      <mesh geometry={nodes.Body_Front_Node.geometry} material={materials.Body_FRONT_26640}>
        <mesh geometry={nodes.Body_Front_Node_1.geometry} material={materials.Body_FRONT_26640} />
        <mesh geometry={nodes.Body_Front_Node_2.geometry} material={materials.Body_FRONT_26640} />
      </mesh>
      <mesh geometry={nodes.Body_Back_Node.geometry} material={materials.Body_FRONT_26640}>
        <mesh geometry={nodes.Body_Back_Node_1.geometry} material={materials.Body_FRONT_26640} />
        <mesh geometry={nodes.Body_Back_Node_2.geometry} material={materials.Body_FRONT_26640} />
      </mesh>
      <mesh geometry={nodes.Sleeves_Node.geometry} material={materials.Body_FRONT_26640}>
        <mesh geometry={nodes.Sleeves_Node_2.geometry} material={materials.Body_FRONT_26640} />
        <mesh geometry={nodes.Sleeves_Node_3.geometry} material={materials.Body_FRONT_26640} />
      </mesh>
      <mesh geometry={nodes.Sleeves_Node_1.geometry} material={materials.Body_FRONT_26640}>
        <mesh geometry={nodes.Sleeves_Node_4.geometry} material={materials.Body_FRONT_26640} />
        <mesh geometry={nodes.Sleeves_Node_5.geometry} material={materials.Body_FRONT_26640} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/ImageToStl.com_T_shirt_gltf.glb')
