'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'es' | 'en';

export const translations = {
  es: {
    nav: {
      gallery: 'Galería',
      faq: 'Preguntas Frecuentes',
    },
    hero: {
      eyebrow: 'Diseño personalizado',
      title: 'SG Signare',
      sub: 'Diseña tu camisa con control total: modelo 3D, tela real y un proceso claro. Sin plantillas genéricas, sin límites.',
      cta1: 'Acceder al Estudio',
      cta2: 'Ver Portafolio',
    },
    features: {
      title: 'Tu diseño. Tu camisa.',
      sub: 'No vendemos opciones prediseñadas. Te damos control total para crear una pieza única.',
      items: [
        {
          title: 'Diseño Libre',
          desc: 'Tu diseño, tus colores, tu estilo. Sin plantillas ni límites en la creatividad.',
        },
        {
          title: 'Vista Previa 3D',
          desc: 'Revisa cómo quedará tu camisa en un modelo 3D antes de confirmar el pedido.',
        },
        {
          title: 'Materiales de Calidad',
          desc: 'Algodón y poliéster de alta calidad con sublimación duradera para uso diario.',
        },
        {
          title: 'Proceso Transparente',
          desc: 'Desde el diseño hasta tu puerta. Sin intermediarios ni pasos innecesarios.',
        },
      ],
    },
    pedido: {
      loading: 'Cargando tu diseño…',
      notFound: {
        title: 'Diseño no encontrado',
        desc: 'No se encontró ningún diseño. Por favor, crea uno primero.',
        cta: 'Volver al Diseñador',
      },
      hero: {
        eyebrow: 'Resumen del pedido',
        title: 'Casi listo',
        sub: 'Revisa tu diseño, completa los datos y finaliza el pedido vía WhatsApp.',
      },
      success: {
        title: 'WhatsApp abierto correctamente',
        desc: 'No olvides adjuntar las capturas y los archivos de tu diseño para procesar el pedido.',
      },
      preview: {
        title: 'Vista del diseño',
        front: 'Frente',
        back: 'Trasero',
        empty: 'Sin diseño para esta vista',
        downloadFront: 'Frente',
        downloadBack: 'Trasero',
      },
      summary: {
        title: 'Resumen del diseño',
        color: 'Color',
        fabric: 'Tela',
        size: 'Talla',
        quantity: 'Cantidad',
        images: 'Imágenes',
        texts: 'Textos',
        pieces: 'pieza(s)',
      },
      form: {
        title: 'Completa tu información',
        requiredNote: 'Los campos marcados con * son obligatorios',
        personalInfo: 'Información personal',
        fullName: 'Nombre completo *',
        namePlaceholder: 'Ingresar aquí su nombre…',
        nameError: 'El nombre es obligatorio',
        deliveryInfo: 'Información de entrega',
        deliveryMethod: 'Método de entrega *',
        pickup: 'Recoger en tienda',
        pickupNote: 'Sin costo adicional',
        delivery: 'Envío a domicilio',
        deliveryNote: 'Coordinar con el equipo',
        address: 'Dirección de envío *',
        addressPlaceholder: 'Calle, número, colonia, código postal, ciudad',
        addressError: 'La dirección es obligatoria para envío a domicilio',
        notesTitle: 'Notas adicionales',
        notesLabel: '¿Algo más que debamos saber? (opcional)',
        notesPlaceholder: 'Ej: referecias de su casa, alguien mas que pueda recoger el pedido, horarios de entrega…',
        notesHelp: 'Puedes incluir preferencias de diseño, necesidades especiales, horarios de entrega, etc.',
        instructionsTitle: 'Instrucciones importantes',
        instructions: [
          'Al confirmar, se abrirá WhatsApp con tu pedido pre-cargado.',
          'Adjunta las 2 capturas (frente y trasero) en el chat.',
          'Además, envía los archivos originales de las imágenes que subiste.',
          'El precio final se confirmará por WhatsApp al revisar tu diseño.',
        ],
        submit: 'Confirmar pedido por WhatsApp',
        submitting: 'Procesando…',
        back: 'Volver al diseñador',
        alertError: 'Por favor, corrige los errores en el formulario.',
        alertNoDesign: 'Error: No se encontró el diseño.',
      },
      footer: 'Diseñador de Playeras 3D · Todos los diseños son revisados antes de producción',
      fabrics: {
        algodon: 'Algodón',
        poliester: 'Poliéster',
        mezcla: 'Mezcla',
        premium: 'Premium',
        none: 'No especificada',
      },
      colors: {
        white: 'Blanco',
        gray: 'Gris',
        graphite: 'Grafito',
        black: 'Negro',
        navy: 'Azul Noche',
      },
      message: {
        title: 'NUEVO PEDIDO DE PLAYERA PERSONALIZADA',
        clientData: 'DATOS DEL CLIENTE',
        name: 'Nombre',
        deliveryDetails: 'DETALLES DE ENTREGA',
        method: 'Método',
        address: 'Dirección',
        designSpecs: 'ESPECIFICACIONES DEL DISEÑO',
        color: 'Color',
        fabric: 'Tela',
        size: 'Talla',
        quantity: 'Cantidad',
        pieces: 'pieza(s)',
        images: 'IMÁGENES',
        imageOn: 'Imagen en',
        dimensions: 'Dimensiones',
        texts: 'TEXTOS',
        location: 'Ubicación',
        font: 'Fuente',
        notes: 'NOTAS ADICIONALES',
        finalSteps: 'IMPORTANTE: PASOS FINALES',
        finalStepsIntro: 'Para completar tu pedido, por favor:',
        step1: 'Envía las 2 capturas del diseño (frente y trasero) a este chat.',
        step2: 'Envía también los archivos originales de las imágenes que subiste.',
        thanks: '¡Gracias por tu preferencia!',
        front: 'Frente',
        back: 'Trasero',
      },
    },
    designer: {
      loadingModel: 'Cargando modelo 3D…',
      modelError: 'No se pudo cargar el modelo 3D',
      sizeLabel: 'Talla',
      title: 'Diseñador 3D',
      subtitle: 'Personaliza',
      sections: {
        color: 'Color de la camisa',
        fabric: 'Tipo de tela',
        size: 'Talla',
        quantity: 'Cantidad',
      },
      colors: { white: 'Blanco', gray: 'Gris', black: 'Negro' },
      fabrics: { algodon: 'Algodón' },
      noImage: 'Sin imagen',
      wide: 'de ancho',
      tall: 'de alto',
      decreaseQty: 'Disminuir cantidad',
      increaseQty: 'Aumentar cantidad',
      addElements: 'Añadir elementos',
      addImage: 'Imagen',
      addText: 'Texto',
      elementTypeImage: 'Imagen',
      elementTypeText: 'Texto',
      removeElement: 'Eliminar elemento',
      realDimensions: 'Dimensiones reales',
      adjustedForSize: 'Ajustado para talla',
      shirtSide: 'Lado de la camisa',
      front: 'Frente',
      back: 'Parte trasera',
      backShort: 'Trasera',
      change: 'Cambiar',
      changeImage: 'Cambiar imagen',
      uploadImage: 'Cargar imagen',
      disableMirror: 'Desactivar espejo',
      enableMirror: 'Activar espejo',
      textLabel: 'Texto',
      textPlaceholder: 'Escribe tu texto',
      fontLabel: 'Fuente',
      colorLabel: 'Color',
      letterStyle: 'Estilo de letra',
      fill: 'Relleno',
      outline: 'Contorno',
      outlineWidth: 'Grosor del contorno —',
      thin: 'Fino',
      thick: 'Grueso',
      controlsTitle: 'Controles interactivos',
      controlCorners: 'Esquinas: escalar proporcionalmente',
      controlEdges: 'Aristas: cambiar ancho o alto',
      controlRotate: 'Círculo: rotar',
      controlMove: 'Centro: mover',
      elementsCount: 'Elementos',
      noElements: 'No hay elementos. Añade una imagen o texto para comenzar.',
      imageHash: 'Imagen',
      alertLoading: 'El modelo 3D aún se está cargando. Por favor, espera un momento.',
      alertModelError: 'No se pudo cargar el modelo 3D. Verifica que el archivo existe en /models/Shirt3D.glb',
      alertSaveError: 'Hubo un error al guardar tu diseño. Por favor, inténtalo de nuevo.',
      orderButton: 'Hacer pedido',
      defaultText: 'Texto ejemplo',
      fontGroups: {
        luxury: 'Alta Moda — Serif de Lujo',
        editorial: 'Editorial — Estilo Vogue & Dior',
        minimal: 'Minimalismo Chic — Sans Serif',
        cursive: 'Cursivas Elegantes — Haute Couture',
        script: 'Script con Carácter',
        condensed: 'Condensadas de Impacto',
        classic: 'Clásicas & Atemporales',
      },
    },
    footer: {
      links: {
        gallery: 'Portafolio',
        faq: 'Preguntas Frecuentes',
        home: 'Inicio',
      },
      copy: 'Todos los derechos reservados.',
      tagline: 'Cuidamos cada detalle del proceso.',
    },
  },
  en: {
    nav: {
      gallery: 'Gallery',
      faq: 'FAQ',
    },
    hero: {
      eyebrow: 'Custom design',
      title: 'SG Signare',
      sub: 'Design your shirt with full control: 3D model, real fabric, and a clear process. No generic templates, no limits.',
      cta1: 'Enter the Studio',
      cta2: 'View Portfolio',
    },
    features: {
      title: 'Your design. Your shirt.',
      sub: "We do not sell pre-made options. We give you full control to create a unique piece.",
      items: [
        {
          title: 'Free Design',
          desc: 'Your design, your colors, your style. No templates or creativity limits.',
        },
        {
          title: '3D Preview',
          desc: 'See how your shirt will look on a 3D model before confirming your order.',
        },
        {
          title: 'Quality Materials',
          desc: 'High-quality cotton and polyester with durable sublimation for daily use.',
        },
        {
          title: 'Clear Process',
          desc: 'From design to your door. No middlemen, no unnecessary steps.',
        },
      ],
    },
    pedido: {
      loading: 'Loading your design…',
      notFound: {
        title: 'Design not found',
        desc: 'No design was found. Please create one first.',
        cta: 'Back to Designer',
      },
      hero: {
        eyebrow: 'Order summary',
        title: 'Almost done',
        sub: 'Review your design, fill in your details, and finish your order via WhatsApp.',
      },
      success: {
        title: 'WhatsApp opened successfully',
        desc: "Don't forget to attach the screenshots and your design files to process the order.",
      },
      preview: {
        title: 'Design preview',
        front: 'Front',
        back: 'Back',
        empty: 'No design for this view',
        downloadFront: 'Front',
        downloadBack: 'Back',
      },
      summary: {
        title: 'Design summary',
        color: 'Color',
        fabric: 'Fabric',
        size: 'Size',
        quantity: 'Quantity',
        images: 'Images',
        texts: 'Texts',
        pieces: 'piece(s)',
      },
      form: {
        title: 'Complete your information',
        requiredNote: 'Fields marked with * are required',
        personalInfo: 'Personal information',
        fullName: 'Full name *',
        namePlaceholder: 'Enter your name here…',
        nameError: 'Name is required',
        deliveryInfo: 'Delivery information',
        deliveryMethod: 'Delivery method *',
        pickup: 'Pick up in store',
        pickupNote: 'No additional cost',
        delivery: 'Home delivery',
        deliveryNote: 'Coordinate with the team',
        address: 'Shipping address *',
        addressPlaceholder: 'Street, number, neighborhood, zip code, city',
        addressError: 'Address is required for home delivery',
        notesTitle: 'Additional notes',
        notesLabel: 'Anything else we should know? (optional)',
        notesPlaceholder: 'E.g.: address of your home, someone else who can pick up the order, delivery times…',
        notesHelp: 'You can include design preferences, special needs, delivery times, etc.',
        instructionsTitle: 'Important instructions',
        instructions: [
          'Once confirmed, WhatsApp will open with your order pre-filled.',
          'Attach the 2 design screenshots (front and back) in the chat.',
          'Also send the original files of the images you uploaded.',
          'The final price will be confirmed via WhatsApp after reviewing your design.',
        ],
        submit: 'Confirm order via WhatsApp',
        submitting: 'Processing…',
        back: 'Back to designer',
        alertError: 'Please fix the errors in the form.',
        alertNoDesign: 'Error: design not found.',
      },
      footer: '3D Shirt Designer · All designs are reviewed before production',
      fabrics: {
        algodon: 'Cotton',
        poliester: 'Polyester',
        mezcla: 'Blend',
        premium: 'Premium',
        none: 'Not specified',
      },
      colors: {
        white: 'White',
        gray: 'Gray',
        graphite: 'Graphite',
        black: 'Black',
        navy: 'Night Blue',
      },
      message: {
        title: 'NEW CUSTOM SHIRT ORDER',
        clientData: 'CUSTOMER DATA',
        name: 'Name',
        deliveryDetails: 'DELIVERY DETAILS',
        method: 'Method',
        address: 'Address',
        designSpecs: 'DESIGN SPECIFICATIONS',
        color: 'Color',
        fabric: 'Fabric',
        size: 'Size',
        quantity: 'Quantity',
        pieces: 'piece(s)',
        images: 'IMAGES',
        imageOn: 'Image on',
        dimensions: 'Dimensions',
        texts: 'TEXTS',
        location: 'Location',
        font: 'Font',
        notes: 'ADDITIONAL NOTES',
        finalSteps: 'IMPORTANT: FINAL STEPS',
        finalStepsIntro: 'To complete your order, please:',
        step1: 'Send the 2 design screenshots (front and back) to this chat.',
        step2: 'Also send the original files of the images you uploaded.',
        thanks: 'Thank you for your business!',
        front: 'Front',
        back: 'Back',
      },
    },
    footer: {
      links: {
        gallery: 'Portfolio',
        faq: 'FAQ',
        home: 'Home',
      },
      copy: 'All rights reserved.',
      tagline: 'We care about every detail of the process.',
    },
  },
};

interface LangCtx {
  lang: Lang;
  t: typeof translations.es;
  toggleLang: () => void;
}

const LangContext = createContext<LangCtx>({
  lang: 'es',
  t: translations.es,
  toggleLang: () => {},
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('es');
  const toggleLang = () => setLang((currentLang) => (currentLang === 'es' ? 'en' : 'es'));

  return (
    <LangContext.Provider value={{ lang, t: translations[lang], toggleLang }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);